import { Nunito } from "next/font/google"
import './globals.css'
import Navbar from "../components/navbar/Navbar"
import ClientOnly from "../components/ClientOnly"
import RegisterModal from "../components/modal/RegisterModal"
import LoginModal from "@/components/modal/LoginModal"
import ToasterProvider from "@/providers/ToasterProvider"
import getCurrentUser from "@/actions/getCurrentUser"
import RentModal from "@/components/modal/RentModal"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const font = Nunito({
  subsets: ["latin"],
  weight: "300"
})

type Props = {
  children: React.ReactNode
}

export default async function RootLayout({ children }: Props) {
  const currentUser = await getCurrentUser()
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <RegisterModal />
          <LoginModal />
          <RentModal />
          <Navbar currentUser={currentUser} />
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
